import json
'''process json file generated by cryptobot
for now, output the list of interest coins by print
'''

def process(file):
    fp = open(file,"rb");
    data = json.load(fp)
    for c in data:
       coininfo = c['coininfo']
       rank = coininfo['Rank']
       #print coininfo['Name']
       if "extrainfo" in c:
           extrainfo = c['extrainfo']
           if len(extrainfo) > 0:
               pass #print "\t",extrainfo["reddit"]
           else:
               print coininfo['Name'],rank,coininfo['Website']
       else:
           #print "\tno extrainfo"
           print coininfo['Name'],"*",rank,coininfo['Website']


if __name__ == '__main__':
    file = "output/crypto_utf8_allonce.json"
    process(file)


