import json
'''process json file generated by cryptobot
for now, output the list of interest coins by print
"missed.txt" is generated by this script. It include all SPA webiste that should be scraped differently
'''

def process(file):
    fp = open(file,"rb");
    data = json.load(fp)
    for c in data:
       coininfo = c['coininfo']
       rank = coininfo['Rank']
       #print coininfo['Name']
       if "extrainfo" in c:
           extrainfo = c['extrainfo']
           if len(extrainfo) > 0:
               pass #print "\t",extrainfo["reddit"]
           else:
               seq = ( coininfo['Name'],coininfo["Symbol"],"%d"%rank,coininfo['Website'] )
               print (",".join(seq))
       else:
           #print "\tno extrainfo"
           print (",".join((coininfo['Name'],coininfo["Symbol"],r"%d"%rank,coininfo['Website'],"*")))


if __name__ == '__main__':
    file = "output/crypto_utf8_allonce.json"
    process(file)


